replicaCount: 1
namespace: springboot-namespace

image:
  repository: localhost:8091/docker-registry/springbootapp
  tag: "20250725141757"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

imagePullSecrets:
  - name: nexus-registry-secret

containerPort: 8080

serviceMonitor:
  enabled: true
  interval: 15s
  path: /actuator/prometheus
  port: http

