replicaCount: 1
namespace: springboot-namespace

image:
  repository: 172.189.107.75:8091/docker-registry/springbootapp
  tag: "20250826073415"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8082
  portName: http

imagePullSecrets:
  - name: nexus-registry-secret

containerPort: 8082

serviceMonitor:
  enabled: true
  interval: 15s
  path: /actuator/prometheus
  port: http


alerts:
  name: springboot-pod-alert
  namespace: monitoring
  release: prometheus-stack
  groupName: springboot.pods
  alertName: SpringbootPodCrashLooping
  targetNamespace: springboot-namespace
  severity: warning

prometheusOperator:
  enabled: true

prometheus:
  serviceMonitorNamespaceSelector:
    matchNames:
      - monitoring
      - springboot-namespace

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
