replicaCount: 1
namespace: springboot-namespace

image:
  repository: host.docker.internal:8091/docker-registry/springbootapp
  tag: "20250804191600"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

imagePullSecrets:
  - name: nexus-registry-secret

containerPort: 8080

serviceMonitor:
  enabled: true
  interval: 15s
  path: /actuator/prometheus
  port: http


alerts:
  name: springboot-pod-alert
  namespace: monitoring
  release: kube-prometheus
  groupName: springboot.pods
  alertName: SpringbootPodCrashLooping
  targetNamespace: springboot-namespace
  severity: warning



